#!/usr/bin/env python3
"""
Parse ta-lib/include/ta_func.h and emit extension/src/generated/talib_catalog.inc
for drift checks and documentation. Regenerate after upgrading TA-Lib:

    python3 scripts/gen_talib_catalog.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    header = root / "ta-lib" / "include" / "ta_func.h"
    out = root / "extension" / "src" / "generated" / "talib_catalog.inc"
    if not header.is_file():
        print(f"Missing {header}", file=sys.stderr)
        return 1

    text = header.read_text(encoding="utf-8", errors="replace")
    # TA_LIB_API TA_RetCode TA_RSI( ... but not TA_S_ float variants
    pat = re.compile(
        r"TA_LIB_API\s+TA_RetCode\s+(TA_[A-Z][A-Z0-9_]*)\s*\(",
        re.MULTILINE,
    )
    names = []
    seen = set()
    for m in pat.finditer(text):
        name = m.group(1)
        if name.startswith("TA_S_"):
            continue
        if name.endswith("_Lookback"):
            continue
        if name in seen:
            continue
        seen.add(name)
        names.append(name)

    names.sort()
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by scripts/gen_talib_catalog.py — do not edit. */",
        f"static constexpr size_t TALIB_CATALOG_COUNT = {len(names)};",
        "static constexpr const char *TALIB_CATALOG_NAMES[] = {",
    ]
    for n in names:
        lines.append(f'    "{n}",')
    lines.append("};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(names)} symbols to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
